### ISSUE TITLE
message.toString() and command line lisibility

### ISSUE THREAD

**Issue by maur1th** [hitgeek/simple-hl7#11]
Just struggled for an hour or so as to why only the last line of my message was printed on command line. I've just started using your library and wonder: if the purpose of the message.toString() method is to print the resulting string on command line, maybe carriage returns could be replaced by line breaks in that function?

**Comment by hitgeek** [comment]
if you look at the git history for header.js, you will see I've gone back and forth on this a couple times. Sorry for the confusion.

originally i used \n because I was using console.log to view the output mostly.
but \n doesn't always work when you actually send the files to other hl7 servers because technically \r "carriage return" is the only legal segment seperator according to the spec. 
I tried \r\n but that had issues because other hl7 servers were processing the \n as the beginning of the next segment, instead of the segment id.
so now its \r, but I never considered how that basically breaks most of the examples.
I will update them to make this clear.

in case you haven't already figured it out, you can override the segment seperator on the message header to get the whole message to print to the console.
``` javascript
msg.header.delimiters.segmentSeperator = '\n' 
```

**Comment by maur1th** [comment]
Alright, thanks for the clarification. Just sent you a pull request to update README accordingly.
https://github.com/hitgeek/simple-hl7/pull/12
