### ISSUE TITLE
Can this be used side-by-side an express web project?

### ISSUE THREAD

**Issue by rjamesnw** [hitgeek/simple-hl7#34]
I'm thinking about adding this to the same project I have, which is an express REST API/web server. Of course the communication modes are different, so there would be one port for the web/rest service, and another for the HL7 server.  Do you foresee any issues? I'm asking because you said simple-hl7 uses express.

**Comment by hitgeek** [comment]
no, you won't have any issues. Actually I designed the v2 api for this exact use case. simple-hl7 doesn't use express directly, it uses a "connect" layer to provide a similar middleware `use(middleware)`  api.

you could actually even share some middleware between the hl7 and rest api server, because the middleware is the same (req, res, next);

that was my intention with the design, but have never actually built a project that does that.

**Comment by rjamesnw** [comment]
Great, thanks. ;)
