### ISSUE TITLE
Correct format of Acknowledge message

### ISSUE THREAD

**Issue by bluepuma77** [hitgeek/simple-hl7#47]
Working with a new communication server we encountered an issue with the ack message. I guess it's the first time a server is actually really checking the ack response.

```
# /simple-hl7/lib/server/tcp-server.js 
var ack = new Message(
    msg.header.getField(3),
    msg.header.getField(4),
    msg.header.getField(1),
    msg.header.getField(2),
    moment().format('YYYYMMDDHHmmss'),
    '',
    ["ACK"],
    'ACK' + moment().format('YYYYMMDDHHmmss'),
    'P',
    '2.3');
ack.addSegment("MSA", "AA", msg.header.getField(8))
```

I created an auto ack with Mirth Connect
```
MSH|^~\&|yyy||ORBIS|xxx|20200910094515.487||ACK^A01^ACK|20200910094515.487|P|2.5
MSA|AA|53304114
```
and also googled and found [HL7 ack on Datica](https://datica.com/academy/hl7-202-the-hl7-ack-acknowledgement-message) 
```
MSH|^~\&|LABADT|DH|EPICADT|DH|201301011228||ACK^A01^ACK |HL7ACK00001|P|2.3
MSA|AA|HL7MSG00001
```
and it seems the "ACK" needs to be accompanied by the message event type. 
Therefore I changed my code to:

```
var ack = new Message(
    hl7.header.getField(3),
    hl7.header.getField(4),
    hl7.header.getField(1),
    hl7.header.getField(2),
    moment().format('YYYYMMDDHHmmss'),
    '',
    ['ACK', hl7.header.getComponent(7, 2), 'ACK'], // <=====
    'ACK' + moment().format('YYYYMMDDHHmmss'),
    'P',
    hl7.header.getField(10), // <-- optionally mirror version
);
ack.addSegment("MSA", "AA", hl7.header.getField(8))
```

**Comment by hitgeek** [comment]
Thanks for the detailed comment. Here is my take..

It looks like MSH 9.2 was optional in HLV 2.3, https://hl7-definition.caristix.com/v2/HL7v2.3/Fields/MSH.9.2 but was then required with HL7 2.5. https://hl7-definition.caristix.com/v2/HL7v2.5/Fields/MSH.9.2

so I think the because you are mirroring the version 2.5, that field is now required so the ACKs become invalid without it. 

i'd be open to a PR that has an option to automatically mirror the ACK version, but I don't think the current default ACK that is version 2.3 needs to change.
