### ISSUE TITLE
Use of Tilde ~ on GetComponent

### ISSUE THREAD

**Issue by bernard-uerm** [hitgeek/simple-hl7#52]
Hi Sir, 

Thank you for your hardwork on this HL7. I'm having issues right now on the tilde on my HL7 Result and it disregards the whole string of the component and returns an empty string. Is there a workaround on this? Thank you so much

**Comment by hitgeek** [comment]
do you have an example? 

If I had to guess you probably need to use getField, instead of getComponent, because the "~" is the field repetition character. 

for example given `NME|Field1|Field2~Field2Repeat|Field3Component1&Field3Component2|Field4`

If you want to get the value`Field2Repeat`, you would use `segment.getField(2, 2)` // the second instance of the second field

if you want `Field3Component2` you would use `segment.getComponent(3, 2)` // the second component of the third field

**Comment by bernard-uerm** [comment]
Hi thanks for this. I've basically used the getField instead of the getComponent. Thank you very much.
